name: Generate ASCII Artwork

on: push

jobs:
  ascii_job:
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON....." >> dragon.txt

    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

    - name: Read file
      run: cat dragon.txt

    - name: List repo files
      run: ls -ltra
