name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON....." >> dragon.txt

    - name: Upload the dragon text file
      uses: actions/upload-artifact@v6
      with:
        name: dragon-text-file
        path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download the dragon text file
      uses: actions/download-artifact@v7
      with:
        name: dragon-text-file

    - name: Test file exists
      run: grep -i "dragon" dragon.txt


  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest

    steps:
    - name: Download the dragon text file
      uses: actions/download-artifact@v7
      with:
        name: dragon-text-file

    - name: Read file
      run: cat dragon.txt

    - name: Deploy...
      run: echo Deploying....
       
  # build_job_1:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v6
  #
  #   - name: List repo files
  #     run: ls -ltra
  #
  #   - name: Executing the ascii script
  #     run: | 
  #       chmod +x ascii-script.sh
  #       ./ascii-script.sh
